os:
  - linux
language: node_js
node_js:
  - "node"
  - "iojs"
  - "8"
  - "7"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6"
    - node_js: "iojs"
before_script:
  - gem install awesome_bot
  - npm i -g ava codecov nyc
  - npm i
script:
  - npm run coverage
after_success:
  - npm run report
