os:
  - linux
language: node_js
node_js:
  - "node"
  - "iojs"
  - "8"
  - "7"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6"
    - node_js: "iojs"

before_install:
  - rvm install 2.2
before_script:
  - gem install awesome_bot
  - npm i -g ava codecov nyc
  - npm i
script:
  - awesome_bot ./.github/*.md ./*.md --allow-ssl --allow-dupe --allow-redirect --allow 403 -w localhost,127.0.0.1,0.0.0.0,api.github.com
  - npm run coverage
after_success:
  - npm run report
